<?php

namespace AppBundle\Repository;

/**
 * OrderProductSubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderProductSubRepository extends \Doctrine\ORM\EntityRepository
{
}
