<?php

namespace AppBundle\Repository;

/**
 * OrderProductDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderProductDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
