<?php

namespace AppBundle\Repository;

/**
 * ProductImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductImagesRepository extends \Doctrine\ORM\EntityRepository
{
}
