# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.image_uploader:
        class: AppBundle\FileUploader
        arguments: ['%product_images_directory%']
    
    api.security.oauth_user_provider:
        class:  AppBundle\Security\UserProvider
        arguments: [ "@doctrine.orm.entity_manager" ]
        
    api.user_manager:
        class: AppBundle\Services\UserManager
        arguments: ["@doctrine.orm.entity_manager", "@security.password_encoder", "@service_container"]
        
    api.api_manager:
        class:  AppBundle\Services\ApiManager
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
